# "New issue" ë²„íŠ¼ì„ ëˆŒë €ì„ ë•Œ í…œí”Œë¦¿ ì„ íƒ í™”ë©´ì„ ë³´ì—¬ì¤„ì§€ ì—¬ë¶€
blank_issues_enabled: false  # 'ë¹ˆ ì´ìŠˆ' ìƒì„±ì„ ë§‰ê³  í…œí”Œë¦¿ ì‚¬ìš©ì„ ê°•ì œí•˜ë ¤ë©´ falseë¡œ ì„¤ì •

# í‘œì‹œí•  ì´ìŠˆ í…œí”Œë¦¿ ëª©ë¡
contact_links:
  - name: "âœ¨ ìƒˆë¡œìš´ ê¸°ëŠ¥ ì œì•ˆ"
    url: https://github.com/aifrica-serengeti/.github/.github/ISSUE_TEMPLATE/feature_request.md
    about: "ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ë‚˜ ê°œì„  ì•„ì´ë””ì–´ë¥¼ ì œì•ˆí•´ì£¼ì„¸ìš”."
  - name: "ğŸ› ë²„ê·¸ ë¦¬í¬íŠ¸"
    url: https://github.com/aifrica-serengeti/.github/.github/ISSUE_TEMPLATE/bug_report.md
    about: "ë¬¸ì œê°€ ë°œìƒí–ˆë‚˜ìš”? ì—¬ê¸°ì— ì•Œë ¤ì£¼ì„¸ìš”."
  - name: "ğŸ› ï¸ ì½”ë“œ ë¦¬í™í† ë§"
    url: https://github.com/aifrica-serengeti/.github/.github/ISSUE_TEMPLATE/refactoring.md
    about: "ì½”ë“œ í’ˆì§ˆ ê°œì„ , ê¸°ìˆ  ë¶€ì±„ í•´ê²° ë“±ì„ ìœ„í•œ ì‘ì—…ì„ ì œì•ˆí•©ë‹ˆë‹¤."
  - name: "ğŸ“„ ë¬¸ì„œ ì‘ì—…"
    url: https://github.com/aifrica-serengeti/.github/.github/ISSUE_TEMPLATE/documentation.md
    about: "README, Wiki ë“± ë¬¸ì„œ ê´€ë ¨ ì‘ì—…ì„ ì œì•ˆí•©ë‹ˆë‹¤."